### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [waiyan93/web-scraping#6]
Hello Wai 👋 , thank you for your effort on the code submission. I am Olivier, CTO at Nimble, and I am happy to be the reviewer for our code review session. Long, one of our Engineering Leads was the one you met in the first interview and he shared with me your scorecard already.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions/concerns and share your opinions about the implementation (if any) during the process.

If we’re aligned on any issue here and you’d like to correct them, please address the issue using proper git-flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready) and I will follow up on those fixes. 😇

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding 🤘

**Comment by olivierobert** [comment]
@waiyan93 I completed the first round of reviews. Have a check 🙏

**Comment by waiyan93** [comment]
Thanks sir.
I will check it.

Best regards,
Wai Yan Htet

**Comment by olivierobert** [comment]
@waiyan93 Thank you for working on doing changes to fix the open issues. However, as stated in the initial message, this is a bi-directional process and I would love to hear back from you on each issue. I expect you to at least provide your feedback and opinion on all the issues open. Without your feedback, my assessment will be incomplete.

**Comment by olivierobert** [comment]
@waiyan93 Thank you for your feedback on the open issues. Since we aim to keep the application process short in time, it is now time to conclude the code challenge review. Thank you for your efforts.

**Comment by waiyan93** [comment]
Thanks you sir.

**Comment by waiyan93** [comment]
Okay sir. I will.

Best regards,
Wai Yan Htet
